name: Pages

on:
  push:
    branches:
      - main  # default branch

jobs:

  pa11y:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: chimeraant/dev@v1.3.3
      - run: pnpm build
      - run: pa11y-ci './_site/**/*.html'

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chimeraant/dev@v1.3.3
      - run: pnpm build
      - uses: filiph/linkcheck@v2.0.23
        with:
          arguments: _site/about/index.html
      - run: pnpm lint:markup
      - run: pnpm lint:text

  lighthouse-performance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chimeraant/dev@v1.3.3
      - run: pnpm build
      - uses: treosh/lighthouse-ci-action@v9
        with:
          configPath: './lighthouserc-performance.json'
          runs: 3

  lighthouse-no-performance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chimeraant/dev@v1.3.3
      - run: pnpm build
      - uses: treosh/lighthouse-ci-action@v9
        with:
          configPath: './lighthouserc-no-performance.json'

  deploy:
    needs: [
      pa11y,
      lighthouse-performance,
      lighthouse-no-performance,
      lint
    ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chimeraant/dev@v1.3.3
      - run: pnpm install
      - run: pnpm build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
