name: Pages

on:
  push:
    branches:
      - main  # default branch

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chimeraant/dev@v1.3.3
      - run: pnpm install
      - run: textlint .
      - run: markdown-link-check content/**/*.md
      - run: pnpm build
      - run: markuplint _site/**/*.html
      - run: pa11y-ci './_site/**/*.html'

  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chimeraant/dev@v1.3.3
      - run: pnpm install
      - run: pnpm build
      - uses: treosh/lighthouse-ci-action@v9
        with:
          configPath: './lighthouserc.json'
          runs: 3
  deploy:
    needs: [
      check,
      lighthouse,
    ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chimeraant/dev@v1.3.3
      - run: pnpm install
      - run: pnpm build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
