name: Pages

on:
  push:
    branches:
      - main

jobs:

  pa11y:
    # https://github.com/pa11y/pa11y-ci/issues/198
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chimeraant/dev@v1.3.3
      - run: pnpm build
      - run: pa11y-ci --config pa11yci.json './_site/**/*.html'

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chimeraant/dev@v1.3.3
      - run: pnpm build
      - run: pnpm check:markup
      - run: pnpm check:text

  lighthouse-performance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chimeraant/dev@v1.3.3
      - run: pnpm build
      - uses: treosh/lighthouse-ci-action@v9
        with:
          configPath: './lighthouserc-performance.json'
          runs: 3

  lighthouse-no-performance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chimeraant/dev@v1.3.3
      - run: pnpm build
      - uses: treosh/lighthouse-ci-action@v9
        with:
          configPath: './lighthouserc-no-performance.json'

  deploy:
    needs: [
      pa11y,
      lighthouse-performance,
      lighthouse-no-performance,
      check
    ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chimeraant/dev@v1.3.3
      - run: pnpm install
      - run: pnpm build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
